[book]
authors = ["chrisbodhi"]
language = "en"
src = "src"
title = "The Almagest Guide"

[build]
extra-watch-dirs = ["../almagest/src"]

[output.html]
additional_css = "theme/fonts/fonts.css"
site-url = "/almagest/"

[rust]
edition = "2024"
