[package]
name = "guide"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
almagest = { path = "../almagest" }
